<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap — TaxiFiumicino.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style type="text/css">
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#333;max-width:75rem;margin:0 auto;padding:2rem}
h1{color:#1a1a1a;font-size:1.5rem;margin-bottom:.5rem}
p.desc{color:#666;margin-bottom:1.5rem;font-size:.9rem}
table{border-collapse:collapse;width:100%;font-size:.85rem}
th{background:#c8956c;color:#fff;text-align:left;padding:.6rem .8rem;font-weight:600}
td{padding:.5rem .8rem;border-bottom:1px solid #eee}
tr:hover td{background:#fef7f0}
a{color:#c8956c;text-decoration:none}
a:hover{text-decoration:underline}
.count{background:#c8956c;color:#fff;padding:.2rem .6rem;border-radius:4px;font-size:.8rem;margin-left:.5rem}
</style>
</head>
<body>
<h1>XML Sitemap<span class="count"><xsl:value-of select="count(sitemap:urlset/sitemap:url|sitemap:sitemapindex/sitemap:sitemap)"/></span></h1>
<p class="desc">Generated by TaxiFiumicino.com — This sitemap helps search engines index the site efficiently.</p>
<xsl:choose>
<xsl:when test="sitemap:sitemapindex">
<table>
<tr><th>Sitemap</th><th>Last Modified</th></tr>
<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
<tr>
<td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="substring(sitemap:lastmod,1,10)"/></td>
</tr>
</xsl:for-each>
</table>
</xsl:when>
<xsl:otherwise>
<table>
<tr><th>URL</th><th>Priority</th><th>Change Freq</th><th>Last Modified</th></tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
<td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
<td><xsl:value-of select="sitemap:priority"/></td>
<td><xsl:value-of select="sitemap:changefreq"/></td>
<td><xsl:value-of select="sitemap:lastmod"/></td>
</tr>
</xsl:for-each>
</table>
</xsl:otherwise>
</xsl:choose>
</body>
</html>
</xsl:template>
</xsl:stylesheet>
