<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>XML Sitemap — TaxiFiumicino.com</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<style type="text/css">
body {
	font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
	color: #444;
	max-width: 80rem;
	margin: 0 auto;
	padding: 2rem;
	background: #f9f7f4;
}
#description {
	background: #fff;
	border: 1px solid #e8e2d9;
	border-radius: 12px;
	padding: 1.5rem 2rem;
	margin-bottom: 2rem;
}
#description h1 {
	font-size: 1.4rem;
	color: #1a1a1a;
	margin: 0 0 .5rem 0;
}
#description p {
	color: #666;
	font-size: .9rem;
	margin: .3rem 0;
	line-height: 1.5;
}
#description a {
	color: #c8956c;
	text-decoration: none;
	font-weight: 600;
}
#description a:hover {
	text-decoration: underline;
}
#content {
	background: #fff;
	border: 1px solid #e8e2d9;
	border-radius: 12px;
	padding: 1.5rem;
	overflow-x: auto;
}
p.expl {
	color: #888;
	font-size: .85rem;
	margin: 0 0 1rem .5rem;
}
p.expl a {
	color: #c8956c;
	font-weight: 600;
	text-decoration: none;
}
table {
	border-collapse: collapse;
	width: 100%;
	font-size: .85rem;
}
th {
	background: linear-gradient(135deg, #c8956c 0%, #d4a574 100%);
	color: #fff;
	text-align: left;
	padding: .7rem 1rem;
	font-weight: 600;
	font-size: .8rem;
	text-transform: uppercase;
	letter-spacing: .03em;
}
th:first-child { border-radius: 8px 0 0 0; }
th:last-child { border-radius: 0 8px 0 0; }
td {
	padding: .6rem 1rem;
	border-bottom: 1px solid #f0ebe4;
	color: #555;
}
tr:hover td {
	background: #fef7f0;
}
td a {
	color: #c8956c;
	text-decoration: none;
	font-weight: 500;
}
td a:hover {
	text-decoration: underline;
	color: #b07a52;
}
.count {
	background: linear-gradient(135deg, #c8956c 0%, #d4a574 100%);
	color: #fff;
	padding: .2rem .7rem;
	border-radius: 6px;
	font-size: .8rem;
	margin-left: .5rem;
	font-weight: 600;
}
.rt-priority {
	text-align: center;
}
.footer-note {
	text-align: center;
	color: #aaa;
	font-size: .75rem;
	margin-top: 1.5rem;
	padding-top: 1rem;
	border-top: 1px solid #eee;
}
</style>
</head>
<body>

<div id="description">
	<h1>XML Sitemap</h1>
	<p>This XML Sitemap is generated by <a href="https://taxifiumicino.com">TaxiFiumicino.com</a> to help search engines like Google, Bing, and Yandex discover and index all pages efficiently.</p>
	<p>Learn more about <a href="https://www.sitemaps.org/" target="_blank">XML Sitemaps</a>.</p>
</div>

<div id="content">
<xsl:choose>
<!-- Sitemap Index -->
<xsl:when test="sitemap:sitemapindex">
<p class="expl">
	This sitemap index contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
</p>
<table>
<tr>
	<th style="width:70%">Sitemap</th>
	<th style="width:30%">Last Modified</th>
</tr>
<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
<tr>
	<td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
	<td><xsl:value-of select="substring(sitemap:lastmod,1,10)"/></td>
</tr>
</xsl:for-each>
</table>
</xsl:when>
<!-- URL Set -->
<xsl:otherwise>
<p class="expl">
	This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
	<xsl:if test="sitemap:urlset/sitemap:url/xhtml:link"> — Including hreflang alternate links for multilingual SEO.</xsl:if>
</p>
<p class="expl"><a href="/sitemap.xml">← Sitemap Index</a></p>
<table>
<tr>
	<th style="width:55%">URL</th>
	<th style="width:10%" class="rt-priority">Images</th>
	<th style="width:10%" class="rt-priority">Priority</th>
	<th style="width:10%">Change Freq</th>
	<th style="width:15%">Last Modified</th>
</tr>
<xsl:for-each select="sitemap:urlset/sitemap:url">
<tr>
	<td><a><xsl:attribute name="href"><xsl:value-of select="sitemap:loc"/></xsl:attribute><xsl:value-of select="sitemap:loc"/></a></td>
	<td class="rt-priority"><xsl:value-of select="count(image:image)"/></td>
	<td class="rt-priority"><xsl:value-of select="sitemap:priority"/></td>
	<td><xsl:value-of select="sitemap:changefreq"/></td>
	<td><xsl:value-of select="sitemap:lastmod"/></td>
</tr>
</xsl:for-each>
</table>
</xsl:otherwise>
</xsl:choose>
</div>

<p class="footer-note">XML Sitemap generated by TaxiFiumicino.com SEO — <a href="https://taxifiumicino.com" style="color:#c8956c;text-decoration:none">taxifiumicino.com</a></p>

</body>
</html>
</xsl:template>
</xsl:stylesheet>
