/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TaxiCiampinoRouteImport } from './routes/taxi-ciampino'
import { Route as TariffeRouteImport } from './routes/tariffe'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as ParentsInfoRouteImport } from './routes/parents-info'
import { Route as ParcheggioFiumicinoRouteImport } from './routes/parcheggio-fiumicino'
import { Route as NumeriRouteImport } from './routes/numeri'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as HotelRomaRouteImport } from './routes/hotel-roma'
import { Route as HotelAeroportoFiumicinoRouteImport } from './routes/hotel-aeroporto-fiumicino'
import { Route as FiumicinoRouteImport } from './routes/fiumicino'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComeChiamareTaxiRomaRouteImport } from './routes/come-chiamare-taxi-roma'
import { Route as AppTaxiRomaRouteImport } from './routes/app-taxi-roma'
import { Route as AeroportoFiumicinoRomaTerminiRouteImport } from './routes/aeroporto-fiumicino-roma-termini'
import { Route as AeroportoFiumicinoRomaCentroRouteImport } from './routes/aeroporto-fiumicino-roma-centro'
import { Route as AeroportiDiRomaRouteImport } from './routes/aeroporti-di-roma'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale.index'
import { Route as LocaleSplatRouteImport } from './routes/$locale.$'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiCiampinoRoute = TaxiCiampinoRouteImport.update({
  id: '/taxi-ciampino',
  path: '/taxi-ciampino',
  getParentRoute: () => rootRouteImport,
} as any)
const TariffeRoute = TariffeRouteImport.update({
  id: '/tariffe',
  path: '/tariffe',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsInfoRoute = ParentsInfoRouteImport.update({
  id: '/parents-info',
  path: '/parents-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcheggioFiumicinoRoute = ParcheggioFiumicinoRouteImport.update({
  id: '/parcheggio-fiumicino',
  path: '/parcheggio-fiumicino',
  getParentRoute: () => rootRouteImport,
} as any)
const NumeriRoute = NumeriRouteImport.update({
  id: '/numeri',
  path: '/numeri',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRomaRoute = HotelRomaRouteImport.update({
  id: '/hotel-roma',
  path: '/hotel-roma',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelAeroportoFiumicinoRoute = HotelAeroportoFiumicinoRouteImport.update({
  id: '/hotel-aeroporto-fiumicino',
  path: '/hotel-aeroporto-fiumicino',
  getParentRoute: () => rootRouteImport,
} as any)
const FiumicinoRoute = FiumicinoRouteImport.update({
  id: '/fiumicino',
  path: '/fiumicino',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeChiamareTaxiRomaRoute = ComeChiamareTaxiRomaRouteImport.update({
  id: '/come-chiamare-taxi-roma',
  path: '/come-chiamare-taxi-roma',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTaxiRomaRoute = AppTaxiRomaRouteImport.update({
  id: '/app-taxi-roma',
  path: '/app-taxi-roma',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroportoFiumicinoRomaTerminiRoute =
  AeroportoFiumicinoRomaTerminiRouteImport.update({
    id: '/aeroporto-fiumicino-roma-termini',
    path: '/aeroporto-fiumicino-roma-termini',
    getParentRoute: () => rootRouteImport,
  } as any)
const AeroportoFiumicinoRomaCentroRoute =
  AeroportoFiumicinoRomaCentroRouteImport.update({
    id: '/aeroporto-fiumicino-roma-centro',
    path: '/aeroporto-fiumicino-roma-centro',
    getParentRoute: () => rootRouteImport,
  } as any)
const AeroportiDiRomaRoute = AeroportiDiRomaRouteImport.update({
  id: '/aeroporti-di-roma',
  path: '/aeroporti-di-roma',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/aeroporti-di-roma': typeof AeroportiDiRomaRoute
  '/aeroporto-fiumicino-roma-centro': typeof AeroportoFiumicinoRomaCentroRoute
  '/aeroporto-fiumicino-roma-termini': typeof AeroportoFiumicinoRomaTerminiRoute
  '/app-taxi-roma': typeof AppTaxiRomaRoute
  '/come-chiamare-taxi-roma': typeof ComeChiamareTaxiRomaRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dmca': typeof DmcaRoute
  '/fiumicino': typeof FiumicinoRoute
  '/hotel-aeroporto-fiumicino': typeof HotelAeroportoFiumicinoRoute
  '/hotel-roma': typeof HotelRomaRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/numeri': typeof NumeriRoute
  '/parcheggio-fiumicino': typeof ParcheggioFiumicinoRoute
  '/parents-info': typeof ParentsInfoRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tariffe': typeof TariffeRoute
  '/taxi-ciampino': typeof TaxiCiampinoRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/aeroporti-di-roma': typeof AeroportiDiRomaRoute
  '/aeroporto-fiumicino-roma-centro': typeof AeroportoFiumicinoRomaCentroRoute
  '/aeroporto-fiumicino-roma-termini': typeof AeroportoFiumicinoRomaTerminiRoute
  '/app-taxi-roma': typeof AppTaxiRomaRoute
  '/come-chiamare-taxi-roma': typeof ComeChiamareTaxiRomaRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dmca': typeof DmcaRoute
  '/fiumicino': typeof FiumicinoRoute
  '/hotel-aeroporto-fiumicino': typeof HotelAeroportoFiumicinoRoute
  '/hotel-roma': typeof HotelRomaRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/numeri': typeof NumeriRoute
  '/parcheggio-fiumicino': typeof ParcheggioFiumicinoRoute
  '/parents-info': typeof ParentsInfoRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tariffe': typeof TariffeRoute
  '/taxi-ciampino': typeof TaxiCiampinoRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/about': typeof AboutRoute
  '/aeroporti-di-roma': typeof AeroportiDiRomaRoute
  '/aeroporto-fiumicino-roma-centro': typeof AeroportoFiumicinoRomaCentroRoute
  '/aeroporto-fiumicino-roma-termini': typeof AeroportoFiumicinoRomaTerminiRoute
  '/app-taxi-roma': typeof AppTaxiRomaRoute
  '/come-chiamare-taxi-roma': typeof ComeChiamareTaxiRomaRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dmca': typeof DmcaRoute
  '/fiumicino': typeof FiumicinoRoute
  '/hotel-aeroporto-fiumicino': typeof HotelAeroportoFiumicinoRoute
  '/hotel-roma': typeof HotelRomaRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/numeri': typeof NumeriRoute
  '/parcheggio-fiumicino': typeof ParcheggioFiumicinoRoute
  '/parents-info': typeof ParentsInfoRoute
  '/prenota': typeof PrenotaRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/tariffe': typeof TariffeRoute
  '/taxi-ciampino': typeof TaxiCiampinoRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/aeroporti-di-roma'
    | '/aeroporto-fiumicino-roma-centro'
    | '/aeroporto-fiumicino-roma-termini'
    | '/app-taxi-roma'
    | '/come-chiamare-taxi-roma'
    | '/contact'
    | '/cookie-policy'
    | '/dmca'
    | '/fiumicino'
    | '/hotel-aeroporto-fiumicino'
    | '/hotel-roma'
    | '/legal-notice'
    | '/numeri'
    | '/parcheggio-fiumicino'
    | '/parents-info'
    | '/prenota'
    | '/privacy-policy'
    | '/tariffe'
    | '/taxi-ciampino'
    | '/terms-of-service'
    | '/$locale/$'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/aeroporti-di-roma'
    | '/aeroporto-fiumicino-roma-centro'
    | '/aeroporto-fiumicino-roma-termini'
    | '/app-taxi-roma'
    | '/come-chiamare-taxi-roma'
    | '/contact'
    | '/cookie-policy'
    | '/dmca'
    | '/fiumicino'
    | '/hotel-aeroporto-fiumicino'
    | '/hotel-roma'
    | '/legal-notice'
    | '/numeri'
    | '/parcheggio-fiumicino'
    | '/parents-info'
    | '/prenota'
    | '/privacy-policy'
    | '/tariffe'
    | '/taxi-ciampino'
    | '/terms-of-service'
    | '/$locale/$'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/about'
    | '/aeroporti-di-roma'
    | '/aeroporto-fiumicino-roma-centro'
    | '/aeroporto-fiumicino-roma-termini'
    | '/app-taxi-roma'
    | '/come-chiamare-taxi-roma'
    | '/contact'
    | '/cookie-policy'
    | '/dmca'
    | '/fiumicino'
    | '/hotel-aeroporto-fiumicino'
    | '/hotel-roma'
    | '/legal-notice'
    | '/numeri'
    | '/parcheggio-fiumicino'
    | '/parents-info'
    | '/prenota'
    | '/privacy-policy'
    | '/tariffe'
    | '/taxi-ciampino'
    | '/terms-of-service'
    | '/$locale/$'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  AboutRoute: typeof AboutRoute
  AeroportiDiRomaRoute: typeof AeroportiDiRomaRoute
  AeroportoFiumicinoRomaCentroRoute: typeof AeroportoFiumicinoRomaCentroRoute
  AeroportoFiumicinoRomaTerminiRoute: typeof AeroportoFiumicinoRomaTerminiRoute
  AppTaxiRomaRoute: typeof AppTaxiRomaRoute
  ComeChiamareTaxiRomaRoute: typeof ComeChiamareTaxiRomaRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DmcaRoute: typeof DmcaRoute
  FiumicinoRoute: typeof FiumicinoRoute
  HotelAeroportoFiumicinoRoute: typeof HotelAeroportoFiumicinoRoute
  HotelRomaRoute: typeof HotelRomaRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  NumeriRoute: typeof NumeriRoute
  ParcheggioFiumicinoRoute: typeof ParcheggioFiumicinoRoute
  ParentsInfoRoute: typeof ParentsInfoRoute
  PrenotaRoute: typeof PrenotaRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TariffeRoute: typeof TariffeRoute
  TaxiCiampinoRoute: typeof TaxiCiampinoRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi-ciampino': {
      id: '/taxi-ciampino'
      path: '/taxi-ciampino'
      fullPath: '/taxi-ciampino'
      preLoaderRoute: typeof TaxiCiampinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tariffe': {
      id: '/tariffe'
      path: '/tariffe'
      fullPath: '/tariffe'
      preLoaderRoute: typeof TariffeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents-info': {
      id: '/parents-info'
      path: '/parents-info'
      fullPath: '/parents-info'
      preLoaderRoute: typeof ParentsInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcheggio-fiumicino': {
      id: '/parcheggio-fiumicino'
      path: '/parcheggio-fiumicino'
      fullPath: '/parcheggio-fiumicino'
      preLoaderRoute: typeof ParcheggioFiumicinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeri': {
      id: '/numeri'
      path: '/numeri'
      fullPath: '/numeri'
      preLoaderRoute: typeof NumeriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-roma': {
      id: '/hotel-roma'
      path: '/hotel-roma'
      fullPath: '/hotel-roma'
      preLoaderRoute: typeof HotelRomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel-aeroporto-fiumicino': {
      id: '/hotel-aeroporto-fiumicino'
      path: '/hotel-aeroporto-fiumicino'
      fullPath: '/hotel-aeroporto-fiumicino'
      preLoaderRoute: typeof HotelAeroportoFiumicinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiumicino': {
      id: '/fiumicino'
      path: '/fiumicino'
      fullPath: '/fiumicino'
      preLoaderRoute: typeof FiumicinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/come-chiamare-taxi-roma': {
      id: '/come-chiamare-taxi-roma'
      path: '/come-chiamare-taxi-roma'
      fullPath: '/come-chiamare-taxi-roma'
      preLoaderRoute: typeof ComeChiamareTaxiRomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-taxi-roma': {
      id: '/app-taxi-roma'
      path: '/app-taxi-roma'
      fullPath: '/app-taxi-roma'
      preLoaderRoute: typeof AppTaxiRomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeroporto-fiumicino-roma-termini': {
      id: '/aeroporto-fiumicino-roma-termini'
      path: '/aeroporto-fiumicino-roma-termini'
      fullPath: '/aeroporto-fiumicino-roma-termini'
      preLoaderRoute: typeof AeroportoFiumicinoRomaTerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeroporto-fiumicino-roma-centro': {
      id: '/aeroporto-fiumicino-roma-centro'
      path: '/aeroporto-fiumicino-roma-centro'
      fullPath: '/aeroporto-fiumicino-roma-centro'
      preLoaderRoute: typeof AeroportoFiumicinoRomaCentroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeroporti-di-roma': {
      id: '/aeroporti-di-roma'
      path: '/aeroporti-di-roma'
      fullPath: '/aeroporti-di-roma'
      preLoaderRoute: typeof AeroportiDiRomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  AboutRoute: AboutRoute,
  AeroportiDiRomaRoute: AeroportiDiRomaRoute,
  AeroportoFiumicinoRomaCentroRoute: AeroportoFiumicinoRomaCentroRoute,
  AeroportoFiumicinoRomaTerminiRoute: AeroportoFiumicinoRomaTerminiRoute,
  AppTaxiRomaRoute: AppTaxiRomaRoute,
  ComeChiamareTaxiRomaRoute: ComeChiamareTaxiRomaRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DmcaRoute: DmcaRoute,
  FiumicinoRoute: FiumicinoRoute,
  HotelAeroportoFiumicinoRoute: HotelAeroportoFiumicinoRoute,
  HotelRomaRoute: HotelRomaRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  NumeriRoute: NumeriRoute,
  ParcheggioFiumicinoRoute: ParcheggioFiumicinoRoute,
  ParentsInfoRoute: ParentsInfoRoute,
  PrenotaRoute: PrenotaRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TariffeRoute: TariffeRoute,
  TaxiCiampinoRoute: TaxiCiampinoRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
